language: java
jdk:
  - openjdk8

branches: # 1.
  only:
    - distribute_test

# Travis CI 서버의 Home
cache: # 2.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build" # 3.

# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - whdgns4288@naver.com