language: java
jdk:
  - openjdk8

branches: # 1.
  only:
    - distribute_test

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"   # jar 만들기

before_deploy:
  - zip -r crawler-web * # 현재 위치의 모든 파일을 해당이름으로 압축
  - mkdir -p deploy
  - mv crawler-web.zip deploy/crawler-web.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: crawler-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - whdgns4288@naver.com