language: java
jdk:
  - openjdk8

branches: # 1.
  only:
    - distribute_test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"   # jar 만들기

# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - whdgns4288@naver.com