version: 0.0
os: linux
files:
  - source:  /     # 현재 프로젝트의 루트 경로
    destination: /home/ubuntu/ec2-user/app/step3/zip   # EC2 내부에서 어떤 디렉토리로 전달할 것인지?
    overwrite: yes  # 덮어쓰기 할 것인지?

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: pp
hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: root