#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-3.cuqgwfh3zcoq.ap-northeast-2.rds.amazonaws.com:3306/project
#    username: admin
#    password: hjk1234
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update  #none , update, validate, create
#    properties:
#      hibernate:
#        format_sql: true*/
#
#logging.level:
#  org.apache.coyote.http11:*/ debug #http 요청 메시지 보기//

server:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      accessKey: AKIAWSWJHSBZ77JKROYU
      secretKey: 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
    s3:
      bucket: myclone
    region:
      static: ap-northeast-2
    stack:
      auto: false

git:
  oauthToken: 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

jwt:
  secret: spring-boot-security-jwt-oauth-project-secret-key