spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://miniproject.cgzxqsxot3o2.ap-northeast-2.rds.amazonaws.com:3306/miniproject?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: skduf564ds
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/final?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: secret

  jpa:
    database: mysql #database 종류 선택
    hibernate:
      ddl-auto: update # none, create, update, validate
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: final
      password: final
      database: final

  mail:
    host: smtp.gmail.com
    port: 587
    username: onepageresumeservice
    password: vwdvbnbundyphlhf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level:
  org.apache.coyote.http11: debug #http 요청 메시지 보기

server:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      accesskey: AKIA3Y4SRQYRDXZQS6PS
      secretkey: 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
    s3:
      bucket: mini-project
    region:
      static: ap-northeast-2
    stack:
      auto: false

git:
  oauthToken: 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

jwt:
  secret: spring-boot-security-jwt-oauth-project-secret-key



